{% set name = "pyepr-quantum" %}
{% set version = "0.8.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlatko-minev/pyEPR/archive/{{ version }}.tar.gz
  sha256: 9a47f1e242b8d16d3fc2dadb8e69060ee0ba2a16170b92645752bd7c0e7014e0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - addict
    - ipython >=7.0.0
    - matplotlib-base >=3.1.0
    - numpy >=1.15.0
    - pandas >=1.0.1
    - pint >=0.8
    - python >=3.6
    - qutip >=3.5.0
    - seaborn >=0.10.0
    - sphinx_rtd_theme >=0.4.0
    - scipy >=1.3.0
    - sympy >=1.3
    - xarray >=0.10.0

test:
  imports:
    - pyEPR

  commands:
    - pip check

  requires:
    - pip
    # Workaround for older version of sphinx_rtd_theme's conda-forge package
    # not specifying its dependencies properly and causing pip check to fail
    - sphinx_rtd_theme >=1.0.0

about:
  home: https://github.com/zlatko-minev/pyEPR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated Python module for the design and quantization of Josephson quantum circuits
  doc_url: https://pyepr-docs.readthedocs.io/
  dev_url: https://github.com/zlatko-minev/pyEPR

extra:
  recipe-maintainers:
    - zlatko-minev
    - wshanks
